### ISSUE TITLE
A question about model weights and testing code

### ISSUE THREAD

**Issue by wangweiran970922** [WilliammmZ/AutoVQE#2]
Hello, may I ask when you can publicly disclose your model weights and test code? Very much looking forward to it

**Comment by WilliammmZ** [comment]
> Hello, may I ask when you can publicly disclose your model weights and test code? Very much looking forward to it
Thanks for your attention～
The config yaml and the model weight:
https://drive.google.com/drive/folders/1VYAmwjvd3owdyZ3XCr40nzPfsliwDLoW?usp=sharing

The shared config file and model parameters represent the current optimal configuration. The test code is included in the open-source repository. You just need to change the config in run bash file (add --eval-only) . Due to a busy schedule recently, it's challenging for me to enhance the readme file at the moment.

**Comment by WilliammmZ** [comment]
public share link：https://drive.google.com/drive/folders/1VYAmwjvd3owdyZ3XCr40nzPfsliwDLoW?usp=sharing
